spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_category_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: asdt87%tv/k
  expiration: 120000